Upgrade markupsafe to fix setuptools error
ImportError: cannot import name 'Feature' from 'setuptools'

Setuptools 46 introduced a breaking change and removed Feature support
https://github.com/pypa/setuptools/pull/1979

Fixed in https://github.com/pallets/markupsafe/pull/24